version: '3.10'

services:

  db:
    image: postgres:14.2-alpine
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: musicapi
      POSTGRES_USER: musicapi
      POSTGRES_PASSWORD: musicapi
    volumes:
      - postgres-data:/var/lib/postgresql/data
 
volumes:
  postgres-data:
    driver: local
