[tool.poetry]
name = "musiccatalogue"
version = "0.1.0"
description = "Music Catalogue Api with Realtime chat"
authors = ["oaksas"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
